server:
  port: 9004

spring:
  security:
    oauth2:
      client:
        registration:
          #google:
            #client-id: <Your client id>
            #client-secret: <Your client secret>
          facebook:
            client-id: <Your facebook Client-Id>
            client-secret: <Your facebook client-secret>>